language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
  - '6'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run report-coverage
  - npm run build
after_success:
  - npm run semantic-release
